# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\proj\Stock4\editor.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 587)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_view = StockView(self.centralWidget)
        self.main_view.setBaseSize(QtCore.QSize(0, 0))
        self.main_view.setObjectName("main_view")
        self.horizontalLayout.addWidget(self.main_view)
        self.widget = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(7, 0, 191, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.loadButton = QtWidgets.QPushButton(self.groupBox)
        self.loadButton.setGeometry(QtCore.QRect(100, 70, 82, 23))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.loadButton.setFont(font)
        self.loadButton.setObjectName("loadButton")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(40, 30, 141, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 41, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.checkBox_gbbq = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_gbbq.setGeometry(QtCore.QRect(20, 60, 70, 17))
        self.checkBox_gbbq.setObjectName("checkBox_gbbq")
        self.checkBox_logcoord = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_logcoord.setGeometry(QtCore.QRect(20, 80, 70, 17))
        self.checkBox_logcoord.setObjectName("checkBox_logcoord")
        self.doubleSpinBox_slope = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_slope.setGeometry(QtCore.QRect(60, 114, 62, 22))
        self.doubleSpinBox_slope.setMinimum(1.0)
        self.doubleSpinBox_slope.setMaximum(1.5)
        self.doubleSpinBox_slope.setSingleStep(0.01)
        self.doubleSpinBox_slope.setObjectName("doubleSpinBox_slope")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 114, 41, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 144, 41, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.doubleSpinBox_margin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_margin.setGeometry(QtCore.QRect(60, 144, 62, 22))
        self.doubleSpinBox_margin.setMinimum(0.0)
        self.doubleSpinBox_margin.setMaximum(100.0)
        self.doubleSpinBox_margin.setSingleStep(5.0)
        self.doubleSpinBox_margin.setProperty("value", 20.0)
        self.doubleSpinBox_margin.setObjectName("doubleSpinBox_margin")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(7, 190, 191, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_overlay1 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_overlay1.setGeometry(QtCore.QRect(20, 30, 70, 17))
        self.checkBox_overlay1.setChecked(False)
        self.checkBox_overlay1.setObjectName("checkBox_overlay1")
        self.radioButton_bookvalue = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_bookvalue.setGeometry(QtCore.QRect(20, 50, 82, 17))
        self.radioButton_bookvalue.setChecked(False)
        self.radioButton_bookvalue.setObjectName("radioButton_bookvalue")
        self.buttonGroup1 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup1.setObjectName("buttonGroup1")
        self.buttonGroup1.addButton(self.radioButton_bookvalue)
        self.checkBox_pc = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_pc.setGeometry(QtCore.QRect(20, 180, 70, 17))
        self.checkBox_pc.setChecked(False)
        self.checkBox_pc.setObjectName("checkBox_pc")
        self.radioButton_VOL = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_VOL.setGeometry(QtCore.QRect(20, 150, 82, 17))
        self.radioButton_VOL.setObjectName("radioButton_VOL")
        self.buttonGroup2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup2.setObjectName("buttonGroup2")
        self.buttonGroup2.addButton(self.radioButton_VOL)
        self.checkBox_indicator_graph = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_indicator_graph.setGeometry(QtCore.QRect(20, 110, 70, 17))
        self.checkBox_indicator_graph.setChecked(True)
        self.checkBox_indicator_graph.setObjectName("checkBox_indicator_graph")
        self.radioButton_MACD = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_MACD.setGeometry(QtCore.QRect(20, 130, 82, 17))
        self.radioButton_MACD.setChecked(True)
        self.radioButton_MACD.setObjectName("radioButton_MACD")
        self.buttonGroup2.addButton(self.radioButton_MACD)
        self.radioButton_MA = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_MA.setGeometry(QtCore.QRect(100, 50, 82, 17))
        self.radioButton_MA.setChecked(True)
        self.radioButton_MA.setObjectName("radioButton_MA")
        self.buttonGroup1.addButton(self.radioButton_MA)
        self.checkBox_grid = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_grid.setGeometry(QtCore.QRect(90, 180, 70, 17))
        self.checkBox_grid.setChecked(True)
        self.checkBox_grid.setObjectName("checkBox_grid")
        self.checkBox_grid_3d = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_grid_3d.setGeometry(QtCore.QRect(140, 180, 41, 17))
        self.checkBox_grid_3d.setChecked(True)
        self.checkBox_grid_3d.setObjectName("checkBox_grid_3d")
        self.checkBox_overlay2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_overlay2.setGeometry(QtCore.QRect(20, 80, 70, 17))
        self.checkBox_overlay2.setChecked(True)
        self.checkBox_overlay2.setObjectName("checkBox_overlay2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 81, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.doubleSpinBox_linewidth = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_linewidth.setGeometry(QtCore.QRect(70, 210, 62, 22))
        self.doubleSpinBox_linewidth.setDecimals(5)
        self.doubleSpinBox_linewidth.setMaximum(10.0)
        self.doubleSpinBox_linewidth.setSingleStep(0.1)
        self.doubleSpinBox_linewidth.setProperty("value", 1.0)
        self.doubleSpinBox_linewidth.setObjectName("doubleSpinBox_linewidth")
        self.radioButton_KDJ = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_KDJ.setGeometry(QtCore.QRect(90, 130, 82, 17))
        self.radioButton_KDJ.setChecked(False)
        self.radioButton_KDJ.setObjectName("radioButton_KDJ")
        self.buttonGroup2.addButton(self.radioButton_KDJ)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.loadButton.clicked.connect(MainWindow.loadButtonClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Stock Data"))
        self.loadButton.setText(_translate("MainWindow", "读取"))
        self.lineEdit.setText(_translate("MainWindow", "sh600000"))
        self.label.setText(_translate("MainWindow", "股票"))
        self.checkBox_gbbq.setText(_translate("MainWindow", "复权"))
        self.checkBox_logcoord.setText(_translate("MainWindow", "对数坐标"))
        self.label_2.setText(_translate("MainWindow", "斜率"))
        self.label_3.setText(_translate("MainWindow", "边缘"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Options"))
        self.checkBox_overlay1.setText(_translate("MainWindow", "主图指标"))
        self.radioButton_bookvalue.setText(_translate("MainWindow", "市净率"))
        self.checkBox_pc.setText(_translate("MainWindow", "PC"))
        self.radioButton_VOL.setText(_translate("MainWindow", "VOL"))
        self.checkBox_indicator_graph.setText(_translate("MainWindow", "指标"))
        self.radioButton_MACD.setText(_translate("MainWindow", "MACD"))
        self.radioButton_MA.setText(_translate("MainWindow", "MA"))
        self.checkBox_grid.setText(_translate("MainWindow", "Grid"))
        self.checkBox_grid_3d.setText(_translate("MainWindow", "3D"))
        self.checkBox_overlay2.setText(_translate("MainWindow", "Overlay2"))
        self.label_4.setText(_translate("MainWindow", "线宽"))
        self.radioButton_KDJ.setText(_translate("MainWindow", "KDJ"))
from StockView import StockView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
